### ISSUE TITLE
TypeError,I can't use it

### ISSUE THREAD

**Issue by xbl** [furzeface/gulp-cache-bust#1] opened 2014-12-24 06:11 UTC
TypeError: undefined is not a function
    at Stream.pipe (stream.js:65:8)
    at Gulp.<anonymous> (/Users/xbl/Documents/project/pet-web/gulpfile.js:26:7)
    at module.exports (/Users/xbl/Documents/project/pet-web/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/xbl/Documents/project/pet-web/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/xbl/Documents/project/pet-web/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/xbl/Documents/project/pet-web/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:372:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:124:16)

**Comment by furzeface** [comment] 2015-01-30 08:58
Common link here seems to be `orchestrator`, I'll take a look into it when I can.

**Comment by furzeface** [comment] 2015-04-11 13:36
Closing as duplicate of #2 - also couldn’t replicate so far.

**Closed by furzeface** 2015-04-11 13:36 UTC
Labels: bug, help wanted
