### ISSUE TITLE
Exclude files

### ISSUE THREAD

**Issue by alvarotrigo** [furzeface/gulp-cache-bust#11] opened 2016-08-31 15:49 UTC
Is there a way to exclude some files from it so the versioning string won't get appened to them?

Having external resources or CDN links adding the versioning string will only force the refreshing for them when its never necessary in those cases.

For example:

``` html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

```

**Comment by davinkevin** [comment] 2016-09-01 03:50
This have been done in the core module : https://github.com/furzeface/cachebust/blob/master/lib/cachebust.js#L57

I think the plug-in isn't up-to-date in npm or in gulp/grunt. I will do a PR on this project and @furzeface  should publish it in NPM.

;)

**Comment by furzeface** [comment] 2016-09-01 08:57
Hey, yeah happy to do this - did I add you as an npm owner on all the repos @davinkevin?

**Comment by alvarotrigo** [comment] 2016-09-01 09:47
@davinkevin thanks for it! Let me know when the new version is available.

**Comment by davinkevin** [comment] 2016-09-02 05:01
The integration with v2.0.1 of cachebust seems to cause error on travis due to base path problem... We will need to investigate on this.

**Comment by davinkevin** [comment] 2016-10-17 04:26
Done in #14 

You could try and confirm / close this issue ;)

**Comment by carlosvicient** [comment] 2017-03-06 13:18
Thanks for this tool!

I can confirm that installing from npm is not working with CDN links.

I do the trick replacing manually

`var protocolRegEx = /^http(s)?/, elements = $('script[src], link[rel=stylesheet][href]');` 

by

 `var protocolRegEx = /^(http(s)?)|\/\//, elements = $('script[src], link[rel=stylesheet][href], link[rel=import][href]');` 

in file _node_modules/gulp-cache-bust/node_modules/cachebust/lib/cachebust.js_

like in [https://github.com/furzeface/cachebust/blob/master/lib/cachebust.js#L57](https://github.com/furzeface/cachebust/blob/master/lib/cachebust.js#L57)

**Closed** 2017-03-11 07:04 UTC

**Comment by davinkevin** [comment] 2017-03-11 07:27
Released new version with this update of cachebust : https://github.com/furzeface/gulp-cache-bust/releases/tag/v1.2.0
